Feature engineering

In [1]:
#data transformation
import pandas as pd
df=pd.read_csv("raw_data (1).csv")
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [3]:
# Applies a function to each row, column, or element.
df2=df.copy()
df2["tax"]=df2["income"].apply(lambda x:"20%" if x>=50000 else "10%")
df2

    id          name   age country   gender   income  tax
0    1      John Doe  29.0     USA     Male  55000.0  20%
1    1      John Doe  29.0     USA     Male  55000.0  20%
2    2    Jane Smith   NaN  Canada   Female  62000.0  20%
3    3          Alex   NaN     USA  Unknown  47000.0  10%
4    4  Maria Garcia  34.0   Spain   Female      NaN  10%
5    5        Li Wei  27.0   China     Male  51000.0  20%
6    6           NaN  45.0   India   Female  73000.0  20%
7    7    Ahmed Khan  38.0     NaN     Male  68000.0  20%
8    8    Rachel Lee  29.0     USA   Female  62000.0  20%
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0  10%
10  10   Emily Davis  31.0     USA      NaN  58000.0  20%

In [4]:
# Maps each value in a Series using a dictionary or function.
gender_map={"Male":"M","Female":"F","Unknown":"U"}
df2["gender"]=df2["gender"].map(gender_map)
df2

    id          name   age country gender   income  tax
0    1      John Doe  29.0     USA      M  55000.0  20%
1    1      John Doe  29.0     USA      M  55000.0  20%
2    2    Jane Smith   NaN  Canada      F  62000.0  20%
3    3          Alex   NaN     USA      U  47000.0  10%
4    4  Maria Garcia  34.0   Spain      F      NaN  10%
5    5        Li Wei  27.0   China      M  51000.0  20%
6    6           NaN  45.0   India      F  73000.0  20%
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%
8    8    Rachel Lee  29.0     USA      F  62000.0  20%
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%
10  10   Emily Davis  31.0     USA    NaN  58000.0  20%

In [5]:
# Creates new columns (or modifies existing ones) and returns a new DataFrame.
df2.assign(new_income=df2["income"]*1.1)

    id          name   age country gender   income  tax  new_income
0    1      John Doe  29.0     USA      M  55000.0  20%     60500.0
1    1      John Doe  29.0     USA      M  55000.0  20%     60500.0
2    2    Jane Smith   NaN  Canada      F  62000.0  20%     68200.0
3    3          Alex   NaN     USA      U  47000.0  10%     51700.0
4    4  Maria Garcia  34.0   Spain      F      NaN  10%         NaN
5    5        Li Wei  27.0   China      M  51000.0  20%     56100.0
6    6           NaN  45.0   India      F  73000.0  20%     80300.0
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%     74800.0
8    8    Rachel Lee  29.0     USA      F  62000.0  20%     68200.0
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%     49500.0
10  10   Emily Davis  31.0     USA    NaN  58000.0  20%     63800.0

In [9]:
# Replaces specific values with new ones.
df2["country"]=df2["country"].replace("USA","US")

In [10]:
df2

    id          name   age country gender   income  tax
0    1      John Doe  29.0      US      M  55000.0  20%
1    1      John Doe  29.0      US      M  55000.0  20%
2    2    Jane Smith   NaN  Canada      F  62000.0  20%
3    3          Alex   NaN      US      U  47000.0  10%
4    4  Maria Garcia  34.0   Spain      F      NaN  10%
5    5        Li Wei  27.0   China      M  51000.0  20%
6    6           NaN  45.0   India      F  73000.0  20%
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%
8    8    Rachel Lee  29.0      US      F  62000.0  20%
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%
10  10   Emily Davis  31.0      US    NaN  58000.0  20%

In [13]:
df2.columns=["Id","Name","Age","Country","Gender","Income","Tax"] #rename all coulmns
df2

    Id          Name   Age Country Gender   Income  Tax
0    1      John Doe  29.0      US      M  55000.0  20%
1    1      John Doe  29.0      US      M  55000.0  20%
2    2    Jane Smith   NaN  Canada      F  62000.0  20%
3    3          Alex   NaN      US      U  47000.0  10%
4    4  Maria Garcia  34.0   Spain      F      NaN  10%
5    5        Li Wei  27.0   China      M  51000.0  20%
6    6           NaN  45.0   India      F  73000.0  20%
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%
8    8    Rachel Lee  29.0      US      F  62000.0  20%
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%
10  10   Emily Davis  31.0      US    NaN  58000.0  20%

In [15]:
df2.rename(columns={"Income":"salary"}) # rename perticular columns

    Id          Name   Age Country Gender   salary  Tax
0    1      John Doe  29.0      US      M  55000.0  20%
1    1      John Doe  29.0      US      M  55000.0  20%
2    2    Jane Smith   NaN  Canada      F  62000.0  20%
3    3          Alex   NaN      US      U  47000.0  10%
4    4  Maria Garcia  34.0   Spain      F      NaN  10%
5    5        Li Wei  27.0   China      M  51000.0  20%
6    6           NaN  45.0   India      F  73000.0  20%
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%
8    8    Rachel Lee  29.0      US      F  62000.0  20%
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%
10  10   Emily Davis  31.0      US    NaN  58000.0  20%

In [17]:
df2.rename(index={1:"First"}) #rename row name

       Id          Name   Age Country Gender   Income  Tax
0       1      John Doe  29.0      US      M  55000.0  20%
First   1      John Doe  29.0      US      M  55000.0  20%
2       2    Jane Smith   NaN  Canada      F  62000.0  20%
3       3          Alex   NaN      US      U  47000.0  10%
4       4  Maria Garcia  34.0   Spain      F      NaN  10%
5       5        Li Wei  27.0   China      M  51000.0  20%
6       6           NaN  45.0   India      F  73000.0  20%
7       7    Ahmed Khan  38.0     NaN      M  68000.0  20%
8       8    Rachel Lee  29.0      US      F  62000.0  20%
9       9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%
10     10   Emily Davis  31.0      US    NaN  58000.0  20%

In [21]:
df2["Income"].sort_values() # sorting based on income
df2.sort_values("Income")

    Id          Name   Age Country Gender   Income  Tax
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%
3    3          Alex   NaN      US      U  47000.0  10%
5    5        Li Wei  27.0   China      M  51000.0  20%
0    1      John Doe  29.0      US      M  55000.0  20%
1    1      John Doe  29.0      US      M  55000.0  20%
10  10   Emily Davis  31.0      US    NaN  58000.0  20%
2    2    Jane Smith   NaN  Canada      F  62000.0  20%
8    8    Rachel Lee  29.0      US      F  62000.0  20%
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%
6    6           NaN  45.0   India      F  73000.0  20%
4    4  Maria Garcia  34.0   Spain      F      NaN  10%

In [22]:
df2.sort_values("Income",ascending=False) # descending sorting

    Id          Name   Age Country Gender   Income  Tax
6    6           NaN  45.0   India      F  73000.0  20%
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%
2    2    Jane Smith   NaN  Canada      F  62000.0  20%
8    8    Rachel Lee  29.0      US      F  62000.0  20%
10  10   Emily Davis  31.0      US    NaN  58000.0  20%
0    1      John Doe  29.0      US      M  55000.0  20%
1    1      John Doe  29.0      US      M  55000.0  20%
5    5        Li Wei  27.0   China      M  51000.0  20%
3    3          Alex   NaN      US      U  47000.0  10%
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%
4    4  Maria Garcia  34.0   Spain      F      NaN  10%

In [25]:
df2=df2.fillna(50)
sorted_df=df2.sort_values(["Income","Age"]) #s sort based on income , if two income are same then sortbased on age
sorted_df

    Id          Name   Age Country Gender   Income  Tax
4    4  Maria Garcia  34.0   Spain      F     50.0  10%
9    9   Carlos Ruiz  50.0  Mexico      M  45000.0  10%
3    3          Alex  50.0      US      U  47000.0  10%
5    5        Li Wei  27.0   China      M  51000.0  20%
0    1      John Doe  29.0      US      M  55000.0  20%
1    1      John Doe  29.0      US      M  55000.0  20%
10  10   Emily Davis  31.0      US     50  58000.0  20%
8    8    Rachel Lee  29.0      US      F  62000.0  20%
2    2    Jane Smith  50.0  Canada      F  62000.0  20%
7    7    Ahmed Khan  38.0      50      M  68000.0  20%
6    6            50  45.0   India      F  73000.0  20%

In [26]:
sorted_df.sort_index() # sort index

    Id          Name   Age Country Gender   Income  Tax
0    1      John Doe  29.0      US      M  55000.0  20%
1    1      John Doe  29.0      US      M  55000.0  20%
2    2    Jane Smith  50.0  Canada      F  62000.0  20%
3    3          Alex  50.0      US      U  47000.0  10%
4    4  Maria Garcia  34.0   Spain      F     50.0  10%
5    5        Li Wei  27.0   China      M  51000.0  20%
6    6            50  45.0   India      F  73000.0  20%
7    7    Ahmed Khan  38.0      50      M  68000.0  20%
8    8    Rachel Lee  29.0      US      F  62000.0  20%
9    9   Carlos Ruiz  50.0  Mexico      M  45000.0  10%
10  10   Emily Davis  31.0      US     50  58000.0  20%

In [27]:
sorted_df.reset_index() # reset the index with preserved values

    index  Id          Name   Age Country Gender   Income  Tax
0       4   4  Maria Garcia  34.0   Spain      F     50.0  10%
1       9   9   Carlos Ruiz  50.0  Mexico      M  45000.0  10%
2       3   3          Alex  50.0      US      U  47000.0  10%
3       5   5        Li Wei  27.0   China      M  51000.0  20%
4       0   1      John Doe  29.0      US      M  55000.0  20%
5       1   1      John Doe  29.0      US      M  55000.0  20%
6      10  10   Emily Davis  31.0      US     50  58000.0  20%
7       8   8    Rachel Lee  29.0      US      F  62000.0  20%
8       2   2    Jane Smith  50.0  Canada      F  62000.0  20%
9       7   7    Ahmed Khan  38.0      50      M  68000.0  20%
10      6   6            50  45.0   India      F  73000.0  20%

In [28]:
sorted_df.reset_index(drop=True) # removes the preserved value

    Id          Name   Age Country Gender   Income  Tax
0    4  Maria Garcia  34.0   Spain      F     50.0  10%
1    9   Carlos Ruiz  50.0  Mexico      M  45000.0  10%
2    3          Alex  50.0      US      U  47000.0  10%
3    5        Li Wei  27.0   China      M  51000.0  20%
4    1      John Doe  29.0      US      M  55000.0  20%
5    1      John Doe  29.0      US      M  55000.0  20%
6   10   Emily Davis  31.0      US     50  58000.0  20%
7    8    Rachel Lee  29.0      US      F  62000.0  20%
8    2    Jane Smith  50.0  Canada      F  62000.0  20%
9    7    Ahmed Khan  38.0      50      M  68000.0  20%
10   6            50  45.0   India      F  73000.0  20%

In [30]:
sorted_df["Ranking"]=sorted_df["Income"].rank() # assign rank based on Income
sorted_df                                       # 1 => lowest rank

    Id          Name   Age Country Gender   Income  Tax  Ranking
4    4  Maria Garcia  34.0   Spain      F     50.0  10%      1.0
9    9   Carlos Ruiz  50.0  Mexico      M  45000.0  10%      2.0
3    3          Alex  50.0      US      U  47000.0  10%      3.0
5    5        Li Wei  27.0   China      M  51000.0  20%      4.0
0    1      John Doe  29.0      US      M  55000.0  20%      5.5
1    1      John Doe  29.0      US      M  55000.0  20%      5.5
10  10   Emily Davis  31.0      US     50  58000.0  20%      7.0
8    8    Rachel Lee  29.0      US      F  62000.0  20%      8.5
2    2    Jane Smith  50.0  Canada      F  62000.0  20%      8.5
7    7    Ahmed Khan  38.0      50      M  68000.0  20%     10.0
6    6            50  45.0   India      F  73000.0  20%     11.0

In [31]:
sorted_df["Ranking"]=sorted_df["Income"].rank(ascending=False)  # 1 => heighest rank
sorted_df

    Id          Name   Age Country Gender   Income  Tax  Ranking
4    4  Maria Garcia  34.0   Spain      F     50.0  10%     11.0
9    9   Carlos Ruiz  50.0  Mexico      M  45000.0  10%     10.0
3    3          Alex  50.0      US      U  47000.0  10%      9.0
5    5        Li Wei  27.0   China      M  51000.0  20%      8.0
0    1      John Doe  29.0      US      M  55000.0  20%      6.5
1    1      John Doe  29.0      US      M  55000.0  20%      6.5
10  10   Emily Davis  31.0      US     50  58000.0  20%      5.0
8    8    Rachel Lee  29.0      US      F  62000.0  20%      3.5
2    2    Jane Smith  50.0  Canada      F  62000.0  20%      3.5
7    7    Ahmed Khan  38.0      50      M  68000.0  20%      2.0
6    6            50  45.0   India      F  73000.0  20%      1.0

In [33]:
sorted_df["Ranking"]=sorted_df["Income"].rank(ascending=False,method="dense")  # assign rounded figuer instead of .5 in the same values
sorted_df

    Id          Name   Age Country Gender   Income  Tax  Ranking
4    4  Maria Garcia  34.0   Spain      F     50.0  10%      9.0
9    9   Carlos Ruiz  50.0  Mexico      M  45000.0  10%      8.0
3    3          Alex  50.0      US      U  47000.0  10%      7.0
5    5        Li Wei  27.0   China      M  51000.0  20%      6.0
0    1      John Doe  29.0      US      M  55000.0  20%      5.0
1    1      John Doe  29.0      US      M  55000.0  20%      5.0
10  10   Emily Davis  31.0      US     50  58000.0  20%      4.0
8    8    Rachel Lee  29.0      US      F  62000.0  20%      3.0
2    2    Jane Smith  50.0  Canada      F  62000.0  20%      3.0
7    7    Ahmed Khan  38.0      50      M  68000.0  20%      2.0
6    6            50  45.0   India      F  73000.0  20%      1.0

In [34]:
sorted_df["Ranking"]=sorted_df["Income"].rank(ascending=False,method="min")  # assing lowest rank in the same values
sorted_df

    Id          Name   Age Country Gender   Income  Tax  Ranking
4    4  Maria Garcia  34.0   Spain      F     50.0  10%     11.0
9    9   Carlos Ruiz  50.0  Mexico      M  45000.0  10%     10.0
3    3          Alex  50.0      US      U  47000.0  10%      9.0
5    5        Li Wei  27.0   China      M  51000.0  20%      8.0
0    1      John Doe  29.0      US      M  55000.0  20%      6.0
1    1      John Doe  29.0      US      M  55000.0  20%      6.0
10  10   Emily Davis  31.0      US     50  58000.0  20%      5.0
8    8    Rachel Lee  29.0      US      F  62000.0  20%      3.0
2    2    Jane Smith  50.0  Canada      F  62000.0  20%      3.0
7    7    Ahmed Khan  38.0      50      M  68000.0  20%      2.0
6    6            50  45.0   India      F  73000.0  20%      1.0

In [35]:
sorted_df["Ranking"]=sorted_df["Income"].rank(ascending=False,method="max")  # assign heighest rang in the same values
sorted_df

    Id          Name   Age Country Gender   Income  Tax  Ranking
4    4  Maria Garcia  34.0   Spain      F     50.0  10%     11.0
9    9   Carlos Ruiz  50.0  Mexico      M  45000.0  10%     10.0
3    3          Alex  50.0      US      U  47000.0  10%      9.0
5    5        Li Wei  27.0   China      M  51000.0  20%      8.0
0    1      John Doe  29.0      US      M  55000.0  20%      7.0
1    1      John Doe  29.0      US      M  55000.0  20%      7.0
10  10   Emily Davis  31.0      US     50  58000.0  20%      5.0
8    8    Rachel Lee  29.0      US      F  62000.0  20%      4.0
2    2    Jane Smith  50.0  Canada      F  62000.0  20%      4.0
7    7    Ahmed Khan  38.0      50      M  68000.0  20%      2.0
6    6            50  45.0   India      F  73000.0  20%      1.0

In [37]:
sorted_df[["Id","Name","Country","Gender","Income","Tax","Age"]] #reorder coloumns

    Id          Name Country Gender   Income  Tax   Age
4    4  Maria Garcia   Spain      F     50.0  10%  34.0
9    9   Carlos Ruiz  Mexico      M  45000.0  10%  50.0
3    3          Alex      US      U  47000.0  10%  50.0
5    5        Li Wei   China      M  51000.0  20%  27.0
0    1      John Doe      US      M  55000.0  20%  29.0
1    1      John Doe      US      M  55000.0  20%  29.0
10  10   Emily Davis      US     50  58000.0  20%  31.0
8    8    Rachel Lee      US      F  62000.0  20%  29.0
2    2    Jane Smith  Canada      F  62000.0  20%  50.0
7    7    Ahmed Khan      50      M  68000.0  20%  38.0
6    6            50   India      F  73000.0  20%  45.0

In [2]:
df #original data

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [6]:
#task-shift id column to the end
df3=df.copy()  # way 1
df3[["name","age","country","gender","income","id"]]

            name   age country   gender   income  id
0       John Doe  29.0     USA     Male  55000.0   1
1       John Doe  29.0     USA     Male  55000.0   1
2     Jane Smith   NaN  Canada   Female  62000.0   2
3           Alex   NaN     USA  Unknown  47000.0   3
4   Maria Garcia  34.0   Spain   Female      NaN   4
5         Li Wei  27.0   China     Male  51000.0   5
6            NaN  45.0   India   Female  73000.0   6
7     Ahmed Khan  38.0     NaN     Male  68000.0   7
8     Rachel Lee  29.0     USA   Female  62000.0   8
9    Carlos Ruiz   NaN  Mexico     Male  45000.0   9
10   Emily Davis  31.0     USA      NaN  58000.0  10

In [7]:
# way 2
new_column_order=[col for col in df3.columns if col!="id"]+["id"]
print(new_column_order)

['name', 'age', 'country', 'gender', 'income', 'id']

In [8]:
df3[new_column_order]

            name   age country   gender   income  id
0       John Doe  29.0     USA     Male  55000.0   1
1       John Doe  29.0     USA     Male  55000.0   1
2     Jane Smith   NaN  Canada   Female  62000.0   2
3           Alex   NaN     USA  Unknown  47000.0   3
4   Maria Garcia  34.0   Spain   Female      NaN   4
5         Li Wei  27.0   China     Male  51000.0   5
6            NaN  45.0   India   Female  73000.0   6
7     Ahmed Khan  38.0     NaN     Male  68000.0   7
8     Rachel Lee  29.0     USA   Female  62000.0   8
9    Carlos Ruiz   NaN  Mexico     Male  45000.0   9
10   Emily Davis  31.0     USA      NaN  58000.0  10