In [1]:
import pandas as pd
df=pd.read_csv("raw_data (1).csv")
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [3]:
# Grouping & aggregation of data
df.groupby("country")["income"].mean() # mean income for each country

country
Canada    62000.0
China     51000.0
India     73000.0
Mexico    45000.0
Spain         NaN
USA       55400.0
Name: income, dtype: float64

In [5]:
df.groupby("country")["income"].min() # minimum income of each country

country
Canada    62000.0
China     51000.0
India     73000.0
Mexico    45000.0
Spain         NaN
USA       47000.0
Name: income, dtype: float64

In [6]:
df.groupby("country")["income"].max() # maximum income of each country

country
Canada    62000.0
China     51000.0
India     73000.0
Mexico    45000.0
Spain         NaN
USA       62000.0
Name: income, dtype: float64

In [7]:
df.groupby("gender")["income"].mean() # mean income of each gender

gender
Female     65666.666667
Male       54800.000000
Unknown    47000.000000
Name: income, dtype: float64

In [12]:
df.groupby("country")["income"].agg(["mean","min","max"]) #multiple function together
# or
df.groupby("country")["income"].agg(avg_salary="mean",min_salary="min",max_salary="max")

         avg_dalary  min_salary  max_salary
country
Canada      62000.0     62000.0     62000.0
China       51000.0     51000.0     51000.0
India       73000.0     73000.0     73000.0
Mexico      45000.0     45000.0     45000.0
Spain           NaN         NaN         NaN
USA         55400.0     47000.0     62000.0

In [ ]:
df.g