In [2]:
import pandas as pd

In [2]:
#datafram
info={
    "Name" : ["sanchali","rima","debu","adrija"],
    "CGPA" : [9.5,7.5,8.9,9.7]
}
df=pd.DataFrame(info) #converted the info dictionary into 2d labelled array / table
print(df)

       Name  CGPA
0  sanchali   9.5
1      rima   7.5
2      debu   8.9
3    adrija   9.7

In [7]:
df

       Name  CGPA
0  sanchali   9.5
1      rima   7.5
2      debu   8.9
3    adrija   9.7

In [8]:
#series
s=pd.Series(["rima","puma","nina","uma","lila"])
print(s)
#index based acess
print(s[2])

0    rima
1    puma
2    nina
3     uma
4    lila
dtype: object
nina

In [12]:
#custom lebels
marks=pd.Series([20,19,21,20,22],index=["sanchali","nina","dev","gopal","akash"])
print(marks)

#lebel based access
print(marks["dev"])
print(marks.index)

sanchali    20
nina        19
dev         21
gopal       20
akash       22
dtype: int64
21
Index(['sanchali', 'nina', 'dev', 'gopal', 'akash'], dtype='object')

In [7]:
# Series properties: vectorised operations are allowed
s1=pd.Series([1,2,3,4,5])
s2=pd.Series([10,20,30,40,50])
print(s1+s2)
#mutable values
s1[0]=10
print(s1+s2)
# immutable size - cannot add or delete any element but can be stored in new series
changed_s1=s1.drop(0)
print(s1)
print(changed_s1)

0    11
1    22
2    33
3    44
4    55
dtype: int64
0    20
1    22
2    33
3    44
4    55
dtype: int64
0    10
1     2
2     3
3     4
4     5
dtype: int64
1    2
2    3
3    4
4    5
dtype: int64

In [11]:
#datafram-can be created by disctionary of lists
info={
    "name":["Sanchali","Adam","Eve","Bob"],
    "age":[20,21,22,19],
    "GPA":[9.5,8.6,7.2,10.0]
}

students=pd.DataFrame(info)
students

       name  age   GPA
0  Sanchali   20   9.5
1      Adam   21   8.6
2       Eve   22   7.2
3       Bob   19  10.0

In [13]:
print(students.index) #row operatison
print(students.columns) #column operation

RangeIndex(start=0, stop=4, step=1)
Index(['name', 'age', 'GPA'], dtype='object')

In [15]:
#can also be created by list of lists
info=pd.DataFrame([["sanchali",20],["Uma",21],["shila",40]],columns=["name","age"])
info

       name  age
0  sanchali   20
1       Uma   21
2     shila   40

In [16]:
#can be created by NumPy arrays

import numpy as np
np_arr=np.array([[1,2,3],[4,5,6]])
df=pd.DataFrame(np_arr,columns=["A","B","C"])
df

   A  B  C
0  1  2  3
1  4  5  6

In [17]:
#working with csv
df=pd.read_csv("employee_data.csv")
print(df)

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000